'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SelectPdf.Samples

    Partial Public Class automatic_bookmarks

        '''<summary>
        '''LnkTest control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LnkTest As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''TxtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TxtElements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtElements As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''BtnCreatePdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnCreatePdf As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
