'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SelectPdf.Samples

    Partial Public Class convert_url_to_pdf

        '''<summary>
        '''TxtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DdlPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DdlPageSize As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DdlPageOrientation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DdlPageOrientation As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''TxtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''TxtHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''BtnCreatePdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnCreatePdf As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
