'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SelectPdf.Samples

    Partial Public Class html_to_pdf_headers_and_footers

        '''<summary>
        '''TxtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ChkHeaderFirstPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkHeaderFirstPage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkHeaderOddPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkHeaderOddPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkHeaderEvenPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkHeaderEvenPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TxtHeaderHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtHeaderHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ChkFooterFirstPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkFooterFirstPage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkFooterOddPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkFooterOddPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkFooterEvenPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkFooterEvenPages As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''TxtFooterHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtFooterHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ChkPageNumbering control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkPageNumbering As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''BtnCreatePdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnCreatePdf As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
