'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace SelectPdf.Samples

    Partial Public Class pdf_converter_viewer_preferences

        '''<summary>
        '''TxtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtUrl As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''DdlPageLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DdlPageLayout As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DdlPageMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DdlPageMode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ChkCenterWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkCenterWindow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkDisplayDocTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkDisplayDocTitle As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkFitWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkFitWindow As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkHideMenuBar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkHideMenuBar As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkHideToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkHideToolbar As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ChkHideWindowUI control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkHideWindowUI As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''BtnCreatePdf control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnCreatePdf As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
