'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OfficeAssignments

    '''<summary>
    '''OfficeAssignmentsObjectDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAssignmentsObjectDataSource As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''OfficeAssignmentsValidationSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAssignmentsValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''OfficeAssignmentsGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeAssignmentsGridView As Global.System.Web.UI.WebControls.GridView
End Class
