'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DocumentViewer
    
    Partial Public Class WatermarkPage
        
        '''<summary>
        '''documentViewer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents documentViewer As Global.GleamTech.DocumentUltimate.AspNet.WebForms.DocumentViewerControl
    End Class
End Namespace
