//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMaster
    {
        public int RoomID { get; set; }
        public string RoomNo { get; set; }
        public string RoomType { get; set; }
        public string Prize { get; set; }
    }
}
