'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DocumentConverter
    
    Partial Public Class PossiblePage
        
        '''<summary>
        '''InputFormats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InputFormats As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''OutputFormats control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OutputFormats As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
