//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReport_Example.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.CUSTOMERs = new HashSet<CUSTOMER>();
        }
    
        public long City_ID { get; set; }
        public string City_Name { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMERs { get; set; }
    }
}
