//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShanuSchoppingCart_WCF.Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShanuShoppingDBEntities : DbContext
    {
        public ShanuShoppingDBEntities()
            : base("name=ShanuShoppingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CartDetails> CartDetails { get; set; }
        public virtual DbSet<ItemDetails> ItemDetails { get; set; }
    }
}
