'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Admin


	Public Partial Class admin

		''' <summary>
		''' head control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected head As Global.System.Web.UI.WebControls.ContentPlaceHolder

		''' <summary>
		''' Header control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Header As Global.System.Web.UI.WebControls.ContentPlaceHolder

		''' <summary>
		''' lblLoggedOnUser control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblLoggedOnUser As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' Sidebar control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Sidebar As Global.System.Web.UI.WebControls.ContentPlaceHolder

		''' <summary>
		''' ContentPlaceHolder1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ContentPlaceHolder1 As Global.System.Web.UI.WebControls.ContentPlaceHolder
	End Class
End Namespace
