'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Admin


	Public Partial Class profiles

		''' <summary>
		''' contentForm control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected contentForm As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' ScriptManager1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ScriptManager1 As Global.System.Web.UI.ScriptManager

		''' <summary>
		''' Panel1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected Panel1 As Global.System.Web.UI.WebControls.Panel

		''' <summary>
		''' GridView1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridView1 As Global.System.Web.UI.WebControls.GridView

		''' <summary>
		''' SqlDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

		''' <summary>
		''' GridView1_RoundedCornersExtender control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridView1_RoundedCornersExtender As Global.AjaxControlToolkit.RoundedCornersExtender

		''' <summary>
		''' GridView1_DropShadowExtender control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridView1_DropShadowExtender As Global.AjaxControlToolkit.DropShadowExtender

		''' <summary>
		''' RoleName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected RoleName As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' tbRoleName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected tbRoleName As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' lbAdd control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lbAdd As Global.System.Web.UI.WebControls.LinkButton

		''' <summary>
		''' lbUpdate control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lbUpdate As Global.System.Web.UI.WebControls.LinkButton

		''' <summary>
		''' lbDelete control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lbDelete As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
