
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("2ad68ec3-ecab-4d3c-8a6f-d83b971fc3f7")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("AlumniAssociationModel", "AlumnusDonation", "Alumnus", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Alumnus), "Donation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Donation), True)>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class AlumniAssociationModelContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new AlumniAssociationModelContainer object using the connection string found in the 'AlumniAssociationModelContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=AlumniAssociationModelContainer", "AlumniAssociationModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new AlumniAssociationModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "AlumniAssociationModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new AlumniAssociationModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "AlumniAssociationModelContainer")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Alumni() As ObjectSet(Of Alumnus)
        Get
            If (_Alumni Is Nothing) Then
                _Alumni = MyBase.CreateObjectSet(Of Alumnus)("Alumni")
            End If
            Return _Alumni
        End Get
    End Property

    Private _Alumni As ObjectSet(Of Alumnus)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Donations() As ObjectSet(Of Donation)
        Get
            If (_Donations Is Nothing) Then
                _Donations = MyBase.CreateObjectSet(Of Donation)("Donations")
            End If
            Return _Donations
        End Get
    End Property

    Private _Donations As ObjectSet(Of Donation)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Alumni EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAlumni(ByVal alumnus As Alumnus)
        MyBase.AddObject("Alumni", alumnus)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Donations EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDonations(ByVal donation As Donation)
        MyBase.AddObject("Donations", donation)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AlumniAssociationModel", Name:="Alumnus")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Alumnus
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Alumnus object.
    ''' </summary>
    ''' <param name="alumnusId">Initial value of the AlumnusId property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    Public Shared Function CreateAlumnus(alumnusId As Global.System.Int32, name As Global.System.String) As Alumnus
        Dim alumnus as Alumnus = New Alumnus
        alumnus.AlumnusId = alumnusId
        alumnus.Name = name
        Return alumnus
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AlumnusId() As Global.System.Int32
        Get
            Return _AlumnusId
        End Get
        Set
            If (_AlumnusId <> Value) Then
                OnAlumnusIdChanging(value)
                ReportPropertyChanging("AlumnusId")
                _AlumnusId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("AlumnusId")
                OnAlumnusIdChanged()
            End If
        End Set
    End Property

    Private _AlumnusId As Global.System.Int32
    Private Partial Sub OnAlumnusIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAlumnusIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property

    Private _Name As Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNameChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AlumniAssociationModel", "AlumnusDonation", "Donation")>
     Public Property Donations() As EntityCollection(Of Donation)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Donation)("AlumniAssociationModel.AlumnusDonation", "Donation")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Donation)("AlumniAssociationModel.AlumnusDonation", "Donation", value)
            End If
        End Set
    End Property

    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="AlumniAssociationModel", Name:="Donation")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Donation
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Donation object.
    ''' </summary>
    ''' <param name="donationId">Initial value of the DonationId property.</param>
    ''' <param name="dateAndAmount">Initial value of the DateAndAmount property.</param>
    ''' <param name="alumnusAlumnusId">Initial value of the AlumnusAlumnusId property.</param>
    Public Shared Function CreateDonation(donationId As Global.System.Int32, dateAndAmount As Global.System.String, alumnusAlumnusId As Global.System.Int32) As Donation
        Dim donation as Donation = New Donation
        donation.DonationId = donationId
        donation.DateAndAmount = dateAndAmount
        donation.AlumnusAlumnusId = alumnusAlumnusId
        Return donation
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DonationId() As Global.System.Int32
        Get
            Return _DonationId
        End Get
        Set
            If (_DonationId <> Value) Then
                OnDonationIdChanging(value)
                ReportPropertyChanging("DonationId")
                _DonationId = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("DonationId")
                OnDonationIdChanged()
            End If
        End Set
    End Property

    Private _DonationId As Global.System.Int32
    Private Partial Sub OnDonationIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnDonationIdChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DateAndAmount() As Global.System.String
        Get
            Return _DateAndAmount
        End Get
        Set
            OnDateAndAmountChanging(value)
            ReportPropertyChanging("DateAndAmount")
            _DateAndAmount = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DateAndAmount")
            OnDateAndAmountChanged()
        End Set
    End Property

    Private _DateAndAmount As Global.System.String
    Private Partial Sub OnDateAndAmountChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDateAndAmountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AlumnusAlumnusId() As Global.System.Int32
        Get
            Return _AlumnusAlumnusId
        End Get
        Set
            OnAlumnusAlumnusIdChanging(value)
            ReportPropertyChanging("AlumnusAlumnusId")
            _AlumnusAlumnusId = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("AlumnusAlumnusId")
            OnAlumnusAlumnusIdChanged()
        End Set
    End Property

    Private _AlumnusAlumnusId As Global.System.Int32
    Private Partial Sub OnAlumnusAlumnusIdChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnAlumnusAlumnusIdChanged()
    End Sub

    #End Region
    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("AlumniAssociationModel", "AlumnusDonation", "Alumnus")>
    Public Property Alumnus() As Alumnus
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Alumnus)("AlumniAssociationModel.AlumnusDonation", "Alumnus").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Alumnus)("AlumniAssociationModel.AlumnusDonation", "Alumnus").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AlumnusReference() As EntityReference(Of Alumnus)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Alumnus)("AlumniAssociationModel.AlumnusDonation", "Alumnus")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Alumnus)("AlumniAssociationModel.AlumnusDonation", "Alumnus", value)
            End If
        End Set
    End Property

    #End Region
End Class

#End Region

