 
 
 
 
 
 
 
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Data.Mapping.EntityViewGenerationAttribute(GetType(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets0FC1239392C3790942F6442DE20134B4F36276A026FB29759446CAC0631FA8C8))> 

Namespace Edm_EntityMappingGeneratedViews
    
    '''<Summary>
    '''The type contains views for EntitySets and AssociationSets that were generated at design time.
    '''</Summary>
    Public NotInheritable Class ViewsForBaseEntitySets0FC1239392C3790942F6442DE20134B4F36276A026FB29759446CAC0631FA8C8
        Inherits System.Data.Mapping.EntityViewContainer
        
        '''<Summary>
        '''The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        '''</Summary>
        Public Sub New()
            MyBase.New
            Me.EdmEntityContainerName = "SchoolEntities"
            Me.StoreEntityContainerName = "SchoolModelStoreContainer"
            Me.HashOverMappingClosure = "baf1525ae9733f4e7f1373aa2bafa0f6bf58d79f6163bf7a5426323e5e33f598"
            Me.HashOverAllExtentViews = "6d873cf14e92a257c039b7a2454f67e6418c619aa8ef112da89666f2b1d5cbe4"
            Me.ViewCount = 18
        End Sub
        
        '''<Summary>
        '''The method returns the view for the index given.
        '''</Summary>
        Protected Overrides Function GetViewAt(ByVal index As Integer) As System.Collections.Generic.KeyValuePair(Of String, String)
            If (index = 0) Then
                Return GetView0
            End If
            If (index = 1) Then
                Return GetView1
            End If
            If (index = 2) Then
                Return GetView2
            End If
            If (index = 3) Then
                Return GetView3
            End If
            If (index = 4) Then
                Return GetView4
            End If
            If (index = 5) Then
                Return GetView5
            End If
            If (index = 6) Then
                Return GetView6
            End If
            If (index = 7) Then
                Return GetView7
            End If
            If (index = 8) Then
                Return GetView8
            End If
            If (index = 9) Then
                Return GetView9
            End If
            If (index = 10) Then
                Return GetView10
            End If
            If (index = 11) Then
                Return GetView11
            End If
            If (index = 12) Then
                Return GetView12
            End If
            If (index = 13) Then
                Return GetView13
            End If
            If (index = 14) Then
                Return GetView14
            End If
            If (index = 15) Then
                Return GetView15
            End If
            If (index = 16) Then
                Return GetView16
            End If
            If (index = 17) Then
                Return GetView17
            End If
            Throw New System.IndexOutOfRangeException()
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.Course
        '''</Summary>
        Private Function GetView0() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.Course", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Course"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.Course](T1."& _ 
                    "Course_CourseID, T1.Course_Title, T1.Course_Credits, T1.Course_DepartmentID)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  "& _ 
                    "  FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS Course_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        "& _ 
                    "    T.Title AS Course_Title, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Credits AS Course_Credits, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
                    "      T.DepartmentID AS Course_DepartmentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"     "& _ 
                    "   FROM SchoolEntities.Courses AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.Department
        '''</Summary>
        Private Function GetView1() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.Department", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Department"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.Departm"& _ 
                    "ent](T1.Department_DepartmentID, T1.Department_Name, T1.Department_Budget, T1.De"& _ 
                    "partment_StartDate, T1.Department_Administrator)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
                    "           T.DepartmentID AS Department_DepartmentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Name AS De"& _ 
                    "partment_Name, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Budget AS Department_Budget, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Star"& _ 
                    "tDate AS Department_StartDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Administrator AS Department_Admin"& _ 
                    "istrator, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolEntities.Departments "& _ 
                    "AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.OfficeAssignment
        '''</Summary>
        Private Function GetView2() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.OfficeAssignment", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing OfficeAssignment"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.O"& _ 
                    "fficeAssignment](T1.OfficeAssignment_InstructorID, T1.OfficeAssignment_Location,"& _ 
                    " T1.OfficeAssignment_Timestamp)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Inst"& _ 
                    "ructorID AS OfficeAssignment_InstructorID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Location AS OfficeAss"& _ 
                    "ignment_Location, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Timestamp AS OfficeAssignment_Timestamp, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    "         True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolEntities.OfficeAssignments AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    " ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.OnlineCourse
        '''</Summary>
        Private Function GetView3() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.OnlineCourse", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing OnlineCourse"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.Onlin"& _ 
                    "eCourse](T1.OnlineCourse_CourseID, T1.OnlineCourse_URL)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SEL"& _ 
                    "ECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS OnlineCourse_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.URL AS On"& _ 
                    "lineCourse_URL, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolEntities.Online"& _ 
                    "Courses AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.OnsiteCourse
        '''</Summary>
        Private Function GetView4() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.OnsiteCourse", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing OnsiteCourse"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.Onsit"& _ 
                    "eCourse](T1.OnsiteCourse_CourseID, T1.OnsiteCourse_Location, T1.OnsiteCourse_Day"& _ 
                    "s, T1.OnsiteCourse_Time)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS"& _ 
                    " OnsiteCourse_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Location AS OnsiteCourse_Location, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    "         T.Days AS OnsiteCourse_Days, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Time AS OnsiteCourse_Time,"& _ 
                    " "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolEntities.OnsiteCourses AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
                    "   ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.Person
        '''</Summary>
        Private Function GetView5() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.Person", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Person"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.Person](T1."& _ 
                    "Person_PersonID, T1.Person_LastName, T1.Person_FirstName, T1.Person_HireDate, T1"& _ 
                    ".Person_EnrollmentDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.PersonID AS "& _ 
                    "Person_PersonID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.LastName AS Person_LastName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Fi"& _ 
                    "rstMidName AS Person_FirstName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            TREAT(T AS [SchoolModel.Instructor"& _ 
                    "]).HireDate AS Person_HireDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            TREAT(T AS [SchoolModel.Student])."& _ 
                    "EnrollmentDate AS Person_EnrollmentDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"       "& _ 
                    "     CASE WHEN T IS OF (ONLY [SchoolModel.Instructor]) THEN True ELSE False END "& _ 
                    "AS _from1, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            CASE WHEN T IS OF (ONLY [SchoolModel.Student]) THEN Tru"& _ 
                    "e ELSE False END AS _from2"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolEntities.People AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1"& _ 
                    "")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.StudentGrade
        '''</Summary>
        Private Function GetView6() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.StudentGrade", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing StudentGrade"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.Stude"& _ 
                    "ntGrade](T1.StudentGrade_EnrollmentID, T1.StudentGrade_CourseID, T1.StudentGrade"& _ 
                    "_StudentID, T1.StudentGrade_Grade)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.E"& _ 
                    "nrollmentID AS StudentGrade_EnrollmentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS StudentGra"& _ 
                    "de_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.StudentID AS StudentGrade_StudentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            "& _ 
                    "T.Grade AS StudentGrade_Grade, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM School"& _ 
                    "Entities.StudentGrades AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.CourseInstructor
        '''</Summary>
        Private Function GetView7() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.CourseInstructor", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing CourseInstructor"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.C"& _ 
                    "ourseInstructor](T1.CourseInstructor_CourseID, T1.CourseInstructor_PersonID)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  "& _ 
                    "  FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            Key(T.Course).CourseID AS CourseInstructo"& _ 
                    "r_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            Key(T.Person).PersonID AS CourseInstructor_PersonID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolEntities.CourseInstructor AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
                    "    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.Courses
        '''</Summary>
        Private Function GetView8() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.Courses", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Courses"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Course](T1.Cours"& _ 
                    "e_CourseID, T1.Course_Title, T1.Course_Credits, T1.Course_DepartmentID)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FRO"& _ 
                    "M ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS Course_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T"& _ 
                    ".Title AS Course_Title, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Credits AS Course_Credits, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"           "& _ 
                    " T.DepartmentID AS Course_DepartmentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FR"& _ 
                    "OM SchoolModelStoreContainer.Course AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.Departments
        '''</Summary>
        Private Function GetView9() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.Departments", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing Departments"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Department]("& _ 
                    "T1.Department_DepartmentID, T1.Department_Name, T1.Department_Budget, T1.Departm"& _ 
                    "ent_StartDate, T1.Department_Administrator)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
                    "      T.DepartmentID AS Department_DepartmentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Name AS Departm"& _ 
                    "ent_Name, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Budget AS Department_Budget, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.StartDate"& _ 
                    " AS Department_StartDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Administrator AS Department_Administra"& _ 
                    "tor, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolModelStoreContainer.Depart"& _ 
                    "ment AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.OfficeAssignments
        '''</Summary>
        Private Function GetView10() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.OfficeAssignments", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing OfficeAssignments"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Office"& _ 
                    "Assignment](T1.OfficeAssignment_InstructorID, T1.OfficeAssignment_Location, T1.O"& _ 
                    "fficeAssignment_Timestamp)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Instructo"& _ 
                    "rID AS OfficeAssignment_InstructorID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Location AS OfficeAssignme"& _ 
                    "nt_Location, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Timestamp AS OfficeAssignment_Timestamp, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        "& _ 
                    "    True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolModelStoreContainer.OfficeAssignment AS T"& _ 
                    ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.OnlineCourses
        '''</Summary>
        Private Function GetView11() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.OnlineCourses", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing OnlineCourses"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.OnlineCour"& _ 
                    "se](T1.OnlineCourse_CourseID, T1.OnlineCourse_URL)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS OnlineCourse_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.URL AS OnlineC"& _ 
                    "ourse_URL, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolModelStoreContainer."& _ 
                    "OnlineCourse AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.OnsiteCourses
        '''</Summary>
        Private Function GetView12() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.OnsiteCourses", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing OnsiteCourses"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.OnsiteCour"& _ 
                    "se](T1.OnsiteCourse_CourseID, T1.OnsiteCourse_Location, T1.OnsiteCourse_Days, T1"& _ 
                    ".OnsiteCourse_Time)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS Onsi"& _ 
                    "teCourse_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Location AS OnsiteCourse_Location, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        "& _ 
                    "    T.Days AS OnsiteCourse_Days, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Time AS OnsiteCourse_Time, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  "& _ 
                    "          True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolModelStoreContainer.OnsiteCourse AS"& _ 
                    " T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.People
        '''</Summary>
        Private Function GetView13() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.People", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing People"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        CASE"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            WHEN T1._fro"& _ 
                    "m1 THEN [SchoolModel.Instructor](T1.Person_PersonID, T1.Person_LastName, T1.Pers"& _ 
                    "on_FirstMidName, T1.Instructor_HireDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            ELSE [SchoolModel.Student]"& _ 
                    "(T1.Person_PersonID, T1.Person_LastName, T1.Person_FirstMidName, T1.Student_Enro"& _ 
                    "llmentDate)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        END"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.PersonID AS"& _ 
                    " Person_PersonID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.LastName AS Person_LastName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.F"& _ 
                    "irstName AS Person_FirstMidName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.HireDate AS Instructor_HireDate"& _ 
                    ", "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.EnrollmentDate AS Student_EnrollmentDate, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True A"& _ 
                    "S _from0, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            CASE WHEN T.HireDate IS NOT NULL THEN True ELSE False EN"& _ 
                    "D AS _from1, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            CASE WHEN T.EnrollmentDate IS NOT NULL THEN True ELSE"& _ 
                    " False END AS _from2"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolModelStoreContainer.Person AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
                    "  WHERE (T.HireDate IS NOT NULL OR T.EnrollmentDate IS NOT NULL)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.StudentGrades
        '''</Summary>
        Private Function GetView14() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.StudentGrades", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing StudentGrades"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.StudentGra"& _ 
                    "de](T1.StudentGrade_EnrollmentID, T1.StudentGrade_CourseID, T1.StudentGrade_Stud"& _ 
                    "entID, T1.StudentGrade_Grade)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Enroll"& _ 
                    "mentID AS StudentGrade_EnrollmentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.CourseID AS StudentGrade_Co"& _ 
                    "urseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.StudentID AS StudentGrade_StudentID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.Gra"& _ 
                    "de AS StudentGrade_Grade, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM SchoolModel"& _ 
                    "StoreContainer.StudentGrade AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.CourseInstructor
        '''</Summary>
        Private Function GetView15() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.CourseInstructor", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing CourseInstructor"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.CourseI"& _ 
                    "nstructor](T3.CourseInstructor_Course, T3.CourseInstructor_Person)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)& _ 
                    "        SELECT -- Constructing Course"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            CreateRef(SchoolEntities.Cour"& _ 
                    "ses, row(T2.CourseInstructor_Course_CourseID),[SchoolModel.Course]) AS CourseIns"& _ 
                    "tructor_Course, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T2.CourseInstructor_Person"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"      "& _ 
                    "      SELECT -- Constructing Person"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                CreateRef(SchoolEntities.Pe"& _ 
                    "ople, row(T1.CourseInstructor_Person_PersonID),[SchoolModel.Person]) AS CourseIn"& _ 
                    "structor_Person, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                T1.CourseInstructor_Course_CourseID"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        "& _ 
                    "    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                    T.CourseID AS CourseIns"& _ 
                    "tructor_Course_CourseID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                    T.PersonID AS CourseInstructor_Pe"& _ 
                    "rson_PersonID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                    True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"                FROM School"& _ 
                    "ModelStoreContainer.CourseInstructor AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            ) AS T1"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        ) AS T2"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T3")
        End Function
        
        '''<Summary>
        '''return view for SchoolModelStoreContainer.vInstructorName
        '''</Summary>
        Private Function GetView16() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolModelStoreContainer.vInstructorName", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing vInstructorName"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Store.vI"& _ 
                    "nstructorName](T1.vInstructorName_FullName, T1.vInstructorName_PersonID)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FR"& _ 
                    "OM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.FullName AS vInstructorName_FullName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    "         T.PersonID AS vInstructorName_PersonID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&" "& _ 
                    "       FROM SchoolEntities.InstructorNames AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
        
        '''<Summary>
        '''return view for SchoolEntities.InstructorNames
        '''</Summary>
        Private Function GetView17() As System.Collections.Generic.KeyValuePair(Of String, String)
            Return New System.Collections.Generic.KeyValuePair(Of String, String)("SchoolEntities.InstructorNames", ""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    SELECT VALUE -- Constructing InstructorNames"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        [SchoolModel.Instruct"& _ 
                    "orName](T1.InstructorName_FullName, T1.InstructorName_PersonID)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    FROM ("&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"   "& _ 
                    "     SELECT "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T.FullName AS InstructorName_FullName, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            T"& _ 
                    ".PersonID AS InstructorName_PersonID, "&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"            True AS _from0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"        FROM"& _ 
                    " SchoolModelStoreContainer.vInstructorName AS T"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    ) AS T1")
        End Function
    End Class
End Namespace

 
