'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Courses

    '''<summary>
    '''DepartmentsEntityDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepartmentsEntityDataSource As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''DepartmentsDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepartmentsDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CoursesEntityDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoursesEntityDataSource As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''CoursesGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CoursesGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SearchTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SearchEntityDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchEntityDataSource As Global.System.Web.UI.WebControls.EntityDataSource

    '''<summary>
    '''SearchQueryExtender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchQueryExtender As Global.System.Web.UI.WebControls.QueryExtender

    '''<summary>
    '''SearchGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchGridView As Global.System.Web.UI.WebControls.GridView
End Class
