// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertMethodCreateViewOpened - Use 'AssertMethodCreateViewOpenedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethodCreateViewOpened()
        {
            #region Variable Declarations
            BrowserWindow uIIndexCodedUItestautoWindow = this.UIIndexCodedUItestautoWindow;
            #endregion

            // Verify that the 'Uri' property of 'Index - Coded UI test automation in MVC - Internet...' window ends with '/Users/Create'
            StringAssert.EndsWith(uIIndexCodedUItestautoWindow.Uri.ToString(), this.AssertMethodCreateViewOpenedExpectedValues.UIIndexCodedUItestautoWindowUri, "Page not loaded.");
        }
        
        /// <summary>
        /// AssertMethodUserCreated - Use 'AssertMethodUserCreatedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethodUserCreated()
        {
            #region Variable Declarations
            HtmlCell uIBobCell = this.UIIndexCodedUItestautoWindow.UIIndexCodedUItestautoDocument.UIItemTable.UIBobCell;
            HtmlCell uISmithCell = this.UIIndexCodedUItestautoWindow.UIIndexCodedUItestautoDocument.UIItemTable.UISmithCell;
            HtmlCell uIItem3051996Cell = this.UIIndexCodedUItestautoWindow.UIIndexCodedUItestautoDocument.UIItemTable.UIItem3051996Cell;
            HtmlHyperlink uIBobsmithsomedomaincoHyperlink = this.UIIndexCodedUItestautoWindow.UIIndexCodedUItestautoDocument.UIBobsmithsomedomaincoHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Bob' cell equals 'Bob '
            Assert.AreEqual(this.AssertMethodUserCreatedExpectedValues.UIBobCellInnerText, uIBobCell.InnerText, "User not created.");

            // Verify that the 'InnerText' property of 'Smith' cell equals 'Smith '
            Assert.AreEqual(this.AssertMethodUserCreatedExpectedValues.UISmithCellInnerText, uISmithCell.InnerText, "User not created.");

            // Verify that the 'InnerText' property of '3/05/1996' cell equals '3/05/1996 '
            Assert.AreEqual(this.AssertMethodUserCreatedExpectedValues.UIItem3051996CellInnerText, uIItem3051996Cell.InnerText, "User not created.");

            // Verify that the 'InnerText' property of 'bobsmith@somedomain.com' link equals 'bobsmith@somedomain.com'
            Assert.AreEqual(this.AssertMethodUserCreatedExpectedValues.UIBobsmithsomedomaincoHyperlinkInnerText, uIBobsmithsomedomaincoHyperlink.InnerText, "User not created.");
        }
        
        /// <summary>
        /// RecordedMethodCreateNew
        /// </summary>
        public void RecordedMethodCreateNew()
        {
            #region Variable Declarations
            HtmlHyperlink uICreateNewHyperlink = this.UIIndexCodedUItestautoWindow.UIIndexCodedUItestautoDocument.UICreateNewHyperlink;
            #endregion

            // Click 'Create New' link
            Mouse.Click(uICreateNewHyperlink, new Point(49, 11));
        }
        
        /// <summary>
        /// RecordedMethodIndex - Use 'RecordedMethodIndexParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethodIndex()
        {

            // Go to web page 'http://localhost:3035/' using new browser instance
            this.UIIndexCodedUItestautoWindow.LaunchUrl(new System.Uri(this.RecordedMethodIndexParams.UIIndexCodedUItestautoWindowUrl));
        }
        
        #region Properties
        public virtual AssertMethodCreateViewOpenedExpectedValues AssertMethodCreateViewOpenedExpectedValues
        {
            get
            {
                if ((this.mAssertMethodCreateViewOpenedExpectedValues == null))
                {
                    this.mAssertMethodCreateViewOpenedExpectedValues = new AssertMethodCreateViewOpenedExpectedValues();
                }
                return this.mAssertMethodCreateViewOpenedExpectedValues;
            }
        }
        
        public virtual AssertMethodUserCreatedExpectedValues AssertMethodUserCreatedExpectedValues
        {
            get
            {
                if ((this.mAssertMethodUserCreatedExpectedValues == null))
                {
                    this.mAssertMethodUserCreatedExpectedValues = new AssertMethodUserCreatedExpectedValues();
                }
                return this.mAssertMethodUserCreatedExpectedValues;
            }
        }
        
        public virtual RecordedMethodIndexParams RecordedMethodIndexParams
        {
            get
            {
                if ((this.mRecordedMethodIndexParams == null))
                {
                    this.mRecordedMethodIndexParams = new RecordedMethodIndexParams();
                }
                return this.mRecordedMethodIndexParams;
            }
        }
        
        public UIIndexCodedUItestautoWindow UIIndexCodedUItestautoWindow
        {
            get
            {
                if ((this.mUIIndexCodedUItestautoWindow == null))
                {
                    this.mUIIndexCodedUItestautoWindow = new UIIndexCodedUItestautoWindow();
                }
                return this.mUIIndexCodedUItestautoWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethodCreateViewOpenedExpectedValues mAssertMethodCreateViewOpenedExpectedValues;
        
        private AssertMethodUserCreatedExpectedValues mAssertMethodUserCreatedExpectedValues;
        
        private RecordedMethodIndexParams mRecordedMethodIndexParams;
        
        private UIIndexCodedUItestautoWindow mUIIndexCodedUItestautoWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethodCreateViewOpened'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertMethodCreateViewOpenedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Uri' property of 'Index - Coded UI test automation in MVC - Internet...' window ends with '/Users/Create'
        /// </summary>
        public string UIIndexCodedUItestautoWindowUri = "/Users/Create";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethodUserCreated'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertMethodUserCreatedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Bob' cell equals 'Bob '
        /// </summary>
        public string UIBobCellInnerText = "Bob ";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Smith' cell equals 'Smith '
        /// </summary>
        public string UISmithCellInnerText = "Smith ";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '3/05/1996' cell equals '3/05/1996 '
        /// </summary>
        public string UIItem3051996CellInnerText = "3/05/2016";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'bobsmith@somedomain.com' link equals 'bobsmith@somedomain.com'
        /// </summary>
        public string UIBobsmithsomedomaincoHyperlinkInnerText = "bobsmith@somedomain.com";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethodIndex'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethodIndexParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:3035/' using new browser instance
        /// </summary>
        public string UIIndexCodedUItestautoWindowUrl = "http://localhost:3035/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexCodedUItestautoWindow : BrowserWindow
    {
        
        public UIIndexCodedUItestautoWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Index - Coded UI test automation in MVC";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Index - Coded UI test automation in MVC");
            this.WindowTitles.Add("Create - Coded UI test automation in MVC");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIIndexCodedUItestautoDocument UIIndexCodedUItestautoDocument
        {
            get
            {
                if ((this.mUIIndexCodedUItestautoDocument == null))
                {
                    this.mUIIndexCodedUItestautoDocument = new UIIndexCodedUItestautoDocument(this);
                }
                return this.mUIIndexCodedUItestautoDocument;
            }
        }
        
        public UICreateCodedUItestautDocument UICreateCodedUItestautDocument
        {
            get
            {
                if ((this.mUICreateCodedUItestautDocument == null))
                {
                    this.mUICreateCodedUItestautDocument = new UICreateCodedUItestautDocument(this);
                }
                return this.mUICreateCodedUItestautDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIIndexCodedUItestautoDocument mUIIndexCodedUItestautoDocument;
        
        private UICreateCodedUItestautDocument mUICreateCodedUItestautDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIndexCodedUItestautoDocument : HtmlDocument
    {
        
        public UIIndexCodedUItestautoDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Index - Coded UI test automation in MVC";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3035/";
            this.WindowTitles.Add("Index - Coded UI test automation in MVC");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UICreateNewHyperlink
        {
            get
            {
                if ((this.mUICreateNewHyperlink == null))
                {
                    this.mUICreateNewHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUICreateNewHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Create New";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Users/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3035/Users/Create";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Users/Create\"";
                    this.mUICreateNewHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUICreateNewHyperlink.WindowTitles.Add("Index - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUICreateNewHyperlink;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlHyperlink UIBobsmithsomedomaincoHyperlink
        {
            get
            {
                if ((this.mUIBobsmithsomedomaincoHyperlink == null))
                {
                    this.mUIBobsmithsomedomaincoHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBobsmithsomedomaincoHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBobsmithsomedomaincoHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBobsmithsomedomaincoHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBobsmithsomedomaincoHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "bobsmith@somedomain.com";
                    this.mUIBobsmithsomedomaincoHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIBobsmithsomedomaincoHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBobsmithsomedomaincoHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "mailto:bobsmith@somedomain.com";
                    this.mUIBobsmithsomedomaincoHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBobsmithsomedomaincoHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"mailto:bobsmith@somedomain.com\"";
                    this.mUIBobsmithsomedomaincoHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIBobsmithsomedomaincoHyperlink.WindowTitles.Add("Index - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIBobsmithsomedomaincoHyperlink;
            }
        }
        
        public HtmlDiv UIIndexCreateNewFirstNPane
        {
            get
            {
                if ((this.mUIIndexCreateNewFirstNPane == null))
                {
                    this.mUIIndexCreateNewFirstNPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIIndexCreateNewFirstNPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIIndexCreateNewFirstNPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIIndexCreateNewFirstNPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Index\r\n\r\nCreate New \r\n\r\n\r\nFirst Name \r\n\r";
                    this.mUIIndexCreateNewFirstNPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIIndexCreateNewFirstNPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "container body-content";
                    this.mUIIndexCreateNewFirstNPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"container body-content\"";
                    this.mUIIndexCreateNewFirstNPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "1";
                    this.mUIIndexCreateNewFirstNPane.WindowTitles.Add("Index - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIIndexCreateNewFirstNPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUICreateNewHyperlink;
        
        private UIItemTable mUIItemTable;
        
        private HtmlHyperlink mUIBobsmithsomedomaincoHyperlink;
        
        private HtmlDiv mUIIndexCreateNewFirstNPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "First Name \r\n\r\nLast Name \r\n\r\nEmail \r\n\r\nD";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"table\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "2";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "5";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "table";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Index - Coded UI test automation in MVC");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIBobCell
        {
            get
            {
                if ((this.mUIBobCell == null))
                {
                    this.mUIBobCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIBobCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIBobCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIBobCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIBobCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Bob ";
                    this.mUIBobCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIBobCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIBobCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIBobCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIBobCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUIBobCell.WindowTitles.Add("Index - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIBobCell;
            }
        }
        
        public HtmlCell UISmithCell
        {
            get
            {
                if ((this.mUISmithCell == null))
                {
                    this.mUISmithCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUISmithCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUISmithCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUISmithCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUISmithCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Smith ";
                    this.mUISmithCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUISmithCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUISmithCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUISmithCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUISmithCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUISmithCell.WindowTitles.Add("Index - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUISmithCell;
            }
        }
        
        public HtmlCell UIItem3051996Cell
        {
            get
            {
                if ((this.mUIItem3051996Cell == null))
                {
                    this.mUIItem3051996Cell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem3051996Cell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem3051996Cell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem3051996Cell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem3051996Cell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "3/05/1996 ";
                    this.mUIItem3051996Cell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIItem3051996Cell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "1";
                    this.mUIItem3051996Cell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "3";
                    this.mUIItem3051996Cell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItem3051996Cell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "4";
                    this.mUIItem3051996Cell.WindowTitles.Add("Index - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIItem3051996Cell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIBobCell;
        
        private HtmlCell mUISmithCell;
        
        private HtmlCell mUIItem3051996Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICreateCodedUItestautDocument : HtmlDocument
    {
        
        public UICreateCodedUItestautDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Create - Coded UI test automation in MVC";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Users/Create";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3035/Users/Create";
            this.WindowTitles.Add("Create - Coded UI test automation in MVC");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIFirstNameEdit
        {
            get
            {
                if ((this.mUIFirstNameEdit == null))
                {
                    this.mUIFirstNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "FirstName";
                    this.mUIFirstNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "FirstName";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "First Name";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"FirstName\" class=\"form-control tex";
                    this.mUIFirstNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIFirstNameEdit.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIFirstNameEdit;
            }
        }
        
        public HtmlEdit UILastNameEdit
        {
            get
            {
                if ((this.mUILastNameEdit == null))
                {
                    this.mUILastNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "LastName";
                    this.mUILastNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "LastName";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Last Name";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"LastName\" class=\"form-control text";
                    this.mUILastNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUILastNameEdit.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUILastNameEdit;
            }
        }
        
        public HtmlEdit UIEmailEdit
        {
            get
            {
                if ((this.mUIEmailEdit == null))
                {
                    this.mUIEmailEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "Email";
                    this.mUIEmailEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Email";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Email\" class=\"form-control text-bo";
                    this.mUIEmailEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUIEmailEdit.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIEmailEdit;
            }
        }
        
        public HtmlEdit UIDateofBirthEdit
        {
            get
            {
                if ((this.mUIDateofBirthEdit == null))
                {
                    this.mUIDateofBirthEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDateofBirthEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DateOfBirth";
                    this.mUIDateofBirthEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DateOfBirth";
                    this.mUIDateofBirthEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Date of Birth";
                    this.mUIDateofBirthEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDateofBirthEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDateofBirthEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control text-box single-line hasDatepicker";
                    this.mUIDateofBirthEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DateOfBirth\" class=\"form-control t";
                    this.mUIDateofBirthEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIDateofBirthEdit.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIDateofBirthEdit;
            }
        }
        
        public UIUidatepickerdivPane UIUidatepickerdivPane
        {
            get
            {
                if ((this.mUIUidatepickerdivPane == null))
                {
                    this.mUIUidatepickerdivPane = new UIUidatepickerdivPane(this);
                }
                return this.mUIUidatepickerdivPane;
            }
        }
        
        public HtmlInputButton UICreateButton
        {
            get
            {
                if ((this.mUICreateButton == null))
                {
                    this.mUICreateButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Create";
                    this.mUICreateButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUICreateButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUICreateButton.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUICreateButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIFirstNameEdit;
        
        private HtmlEdit mUILastNameEdit;
        
        private HtmlEdit mUIEmailEdit;
        
        private HtmlEdit mUIDateofBirthEdit;
        
        private UIUidatepickerdivPane mUIUidatepickerdivPane;
        
        private HtmlInputButton mUICreateButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIUidatepickerdivPane : HtmlDiv
    {
        
        public UIUidatepickerdivPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "ui-datepicker-div";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Prev\r\n\r\nNext\r\n\r\nJanFebMarAprMayJunJulAug";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" +
                "\" id=\"ui-datepicker-div\" style=\"left: 259.41px; top: 354.79px; display: block; p" +
                "osition: absolute; z-index: 1;\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "14";
            this.WindowTitles.Add("Create - Coded UI test automation in MVC");
            #endregion
        }
        
        #region Properties
        public HtmlComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUIItemComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = null;
                    this.mUIItemComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = null;
                    this.mUIItemComboBox.SearchProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUIItemComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUIItemComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUIItemComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "21";
                    this.mUIItemComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = "ui-datepicker-year";
                    this.mUIItemComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "class=\"ui-datepicker-year\" data-event=\"c";
                    this.mUIItemComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "2";
                    this.mUIItemComboBox.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        
        public HtmlHyperlink UIItem5Hyperlink
        {
            get
            {
                if ((this.mUIItem5Hyperlink == null))
                {
                    this.mUIItem5Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem5Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem5Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem5Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem5Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "5";
                    this.mUIItem5Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Users/Create";
                    this.mUIItem5Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem5Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3035/Users/Create#";
                    this.mUIItem5Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ui-state-default";
                    this.mUIItem5Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ui-state-default\" href=\"#\"";
                    this.mUIItem5Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "7";
                    this.mUIItem5Hyperlink.WindowTitles.Add("Create - Coded UI test automation in MVC");
                    #endregion
                }
                return this.mUIItem5Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlComboBox mUIItemComboBox;
        
        private HtmlHyperlink mUIItem5Hyperlink;
        #endregion
    }
}
